<?php /*a:1:{s:69:"/www/wwwroot/movieboostvip.com/application/index/view/user/login.html";i:1737603713;}*/ ?>
<html lang="zh"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>login</title><link rel="stylesheet" href="/static_en/css/css.css"><!-- 
		http://forgerock-revue.com
		13555555555
		123456
		
		https://uk-magora-aka.com
		13555555555
		123456
	 --></head><body class="bodybg"><div class="login"><div class="logo"><img src="/static_en/img/Keap-Logo-02.png?v" alt=""><h2> Welcome </h2><!-- <article><p>Sign up or log in today to shop and earn cash!</p><p>Withdrawal to bank account (limited to one</p><p>mobile number)</p></article> --></div><div class="form"><div class="tit"><div class="t"><h2>Login</h2><a href="register.html"><b>Register Account?<b></a></div><div class="b">Please log in to access more content</div></div><form action="" method="post" name="login" onsubmit="return checkLogin()"><div class="item"><p>Username</p><input type="text" name="username" placeholder="Type Here" autocomplete="off"></div><div class="item"><p>Password</p><input type="password" name="password" placeholder="Type Here" autocomplete="off"></div><button type="submit"><img src="/static_en/img/jiantou.png"></button></form></div><div class="foot">Copyright © 2023  The Movieboost All Rights Reserved</div></div><script type="text/javascript" src="/static_en/js/jquery.js"></script><script charset="utf-8" src="/static_new/js/dialog.min.js"></script><script type="text/javascript" src="/static_en/js/public.js"></script><div class="msgpop" style="display: none;"></div><div class="alertpop"><div class="box"><div class="h2">Keap</div><article></article><div class="btn"><a href="javascript:;" onclick="alertHide()">Confirm</a></div></div></div><div class="selectpop"><div class="bg"><div class="box"><ul><li>female</li><li>male</li></ul><div class="selectpopclose" onclick="selectHide()">Cancel</div></div></div></div><div class="loading"><img src="/static_en/img/loading.gif" alt=""><p>loading</p></div><div class="confirmpop"><div class="box"><div class="h2">Keap</div><article></article><div class="btn"><a href="javascript:;" class="confirmHide" onclick="confirmHide()">Cancel</a><a href="javascript:;" class="confirmsubmit">Confirm</a></div></div></div><script type="text/javascript" src="/static_en/js/login.js"></script></body></html>